#!/usr/bin/env python

#title   : xavirus
#coded   : Rex4
#support : Cantix Crew
#Manusia yang hebat adalah manusia yang mampu menghargai karya orang lain.
#NOTE: Recode tak akan membuat anda bisa,melain kan hanya menunjukan kalau anda lammer :)

import os
import sys
import time
import requests
from requests.exceptions import ConnectionError
from mechanize import Browser

# random agent for xavirus
def randomAgentGen():

 userAgent =    ['Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/7.0.5 Safari/537.77.4',
                'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
                'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0',
                'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:31.0) Gecko/20100101 Firefox/31.0',
                'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
                'Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53',
                'Mozilla/5.0 (iPad; CPU OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
                'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:31.0) Gecko/20100101 Firefox/31.0',
                'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
                'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/534.59.10 (KHTML, like Gecko) Version/5.1.9 Safari/534.59.10',
                'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0',
                'Mozilla/5.0 (iPhone; CPU iPhone OS 7_1 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D167 Safari/9537.53',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.74.9 (KHTML, like Gecko) Version/7.0.2 Safari/537.74.9',
                'Mozilla/5.0 (X11; Linux x86_64; rv:30.0) Gecko/20100101 Firefox/30.0',
                'Mozilla/5.0 (iPhone; CPU iPhone OS 7_0_4 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11B554a Safari/9537.53',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.75.14 (KHTML, like Gecko) Version/7.0.3 Safari/537.75.14',
                'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
                'Mozilla/5.0 (Windows NT 5.1; rv:30.0) Gecko/20100101 Firefox/30.0',
                'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36',
                'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
                'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:29.0) Gecko/20100101 Firefox/29.0',
                'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:31.0) Gecko/20100101 Firefox/31.0',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
                'Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) GSA/4.1.0.31802 Mobile/11D257 Safari/9537.53',
                'Mozilla/5.0 (Windows NT 6.2; WOW64; rv:30.0) Gecko/20100101 Firefox/30.0',
                'Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36',
                'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36',
                'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/36.0.1985.125 Chrome/36.0.1985.125 Safari/537.36',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.8; rv:30.0) Gecko/20100101 Firefox/30.0',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10) AppleWebKit/600.1.3 (KHTML, like Gecko) Version/8.0 Safari/600.1.3',
                'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36']


# color for xavirus

R = '\033[31;1m'
G = '\033[32;1m'
Y = '\033[33;1m'
W = '\033[37;1m'
P = '\033[35;1m'

# main area xavirus

os.system('clear')
def main():
	print(R + "\n @@@  @@@   @@@@@@   @@@  @@@  @@@  @@@@@@@   @@@  @@@   @@@@@@   ")
	print(" @@@  @@@  @@@@@@@@  @@@  @@@  @@@  @@@@@@@@  @@@  @@@  @@@@@@@   ")
	print(" @@!  !@@  @@!  @@@  @@!  @@@  @@!  @@!  @@@  @@!  @@@  !@@       ")
	print(" !@!  @!!  !@!  @!@  !@!  @!@  !@!  !@!  @!@  !@!  @!@  !@!       ")
	print("  !@@!@!   @!@!@!@!  @!@  !@!  !!@  @!@!!@!   @!@  !@!  !!@@!!    ")
	print(W + "   @!!!    !!!@!!!!  !@!  !!!  !!!  !!@!@!    !@!  !!!   !!@!!!   ")
	print("  !: :!!   !!:  !!!  :!:  !!:  !!:  !!: :!!   !!:  !!!       !:!  ")
	print(" :!:  !:!  :!:  !:!   ::!!:!   :!:  :!:  !:!  :!:  !:!      !:!   ")
	print("  ::  :::  ::   :::    ::::     ::  ::   :::  ::::: ::  :::: ::   ")
	print("  :   ::    :   : :     :      :     :   : :   : :  :   :: : :    \n")
	print(W + "      Author     : " + R + "Rex4                             ")
	print(W + "      Develoved  : " + R + "Cantix Crew                    ")
	print(W + "      Instagram  : " + R + "@cantix_crew\n")
	print(G + " (" + G + "•" + G + ")" + W + " 1. Trojan")
	print(R + " (" + R + "•" + R + ")" + W + " 2. Malware")
	print(Y + " (" + Y + "•" + Y + ")" + W + " 3. Worm")
	print(P + " (" + P + "•" + P + ")" + W + " x. Exit\n")
	xa = input(' pilih: ' + G)
	if xa == '1':
		Trojan()
	else:
		if xa == '2':
			Malwer()
		else:
			if xa == '3':
				W0rm()
			else:
				if xa == 'x':
					rexa = input(R + ' [?]' + W + ' you want exit ? ' + G + '[y/N] ')
					if rexa == 'y' or rexa == 'Y':
						time.sleep(1)
						print(W + " see you..")
						time.sleep(1)
						print(W + " don't forget smile today :)")
						time.sleep(1)
						sys.exit()
					else:
						print(R + " [!]" + W + " wrong input")
						time.sleep(2)
						os.system('clear')
						main()
		
	
# Trojan area

def Trojan():
	ph = ['628']
	phone = input(G + '\n [•]' + W + ' nomor: ' + G)
	nomor = input(G + ' [•]' + W + ' banyak trojan: [1-20] ' + G)
	time.sleep(1)
	if nomor == '1':
		time.sleep(1)
		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
		time.sleep(1)
		print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
		time.sleep(1)
		print(G + "  [•]" + W + " selesai..")
		time.sleep(3)
		os.system('clear')
		main()
	else:
		if nomor == '2':
			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
			time.sleep(1)
			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
			time.sleep(1)
			print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
			time.sleep(1)
			print(G + "  [•]" + W + " selesai..")
			time.sleep(3)
			os.system('clear')
			main()
		else:
			if nomor == '3':
				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
				time.sleep(1)
				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
				time.sleep(1)
				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
				time.sleep(1)
				print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
				time.sleep(1)
				print(G + "  [•]" + W + " selesai..")
				time.sleep(3)
				os.system('clear')
				main()
			else:
				if nomor == '4':
					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
					time.sleep(1)
					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
					time.sleep(1)
					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
					time.sleep(1)
					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
					time.sleep(1)
					print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
					time.sleep(1)
					print(G + "  [•]" + W + " selesai..")
					time.sleep(3)
					os.system('clear')
					main()
				else:
					if nomor == '5':
						print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
						time.sleep(1)
						print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
						time.sleep(1)
						print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
						time.sleep(1)
						print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
						time.sleep(1)
						print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
						time.sleep(1)
						print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
						time.sleep(1)
						print(G + "  [•]" + W + " selesai..")
						time.sleep(3)
						os.system('clear')
						main()
					else:
						if nomor == '6':
							print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
							time.sleep(1)
							print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
							time.sleep(1)
							print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
							time.sleep(1)
							print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
							time.sleep(1)
							print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
							time.sleep(1)
							print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
							time.sleep(1)
							print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
							time.sleep(1)
							print(G + "  [•]" + W + " selesai..")
							time.sleep(3)
							os.system('clear')
							main()
						else:
							if nomor == '7':
								print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
								time.sleep(1)
								print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
								time.sleep(1)
								print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
								time.sleep(1)
								print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
								time.sleep(1)
								print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
								time.sleep(1)
								print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
								time.sleep(1)
								print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
								time.sleep(1)
								print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
								time.sleep(1)
								print(G + "  [•]" + W + " selesai..")
								time.sleep(3)
								os.system('clear')
								main()
							else:
								if nomor == '8':
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
									time.sleep(1)
									print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
									time.sleep(1)
									print(G + "  [•]" + W + " selesai..")
									time.sleep(3)
									os.system('clear')
									main()
								else:
									if nomor == '9':
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
										time.sleep(1)
										print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
										time.sleep(1)
										print(G + "  [•]" + W + " selesai..")
										time.sleep(3)
										os.system('clear')
										main()
									else:
										if nomor == '10':
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
											time.sleep(1)
											print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
											time.sleep(1)
											print(G + "  [•]" + W + " selesai..")
											time.sleep(3)
											os.system('clear')
											main()
										else:
											if nomor == '11':
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "   [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
												time.sleep(1)
												print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
												time.sleep(1)
												print(G + "  [•]" + W + " selesai..")
												time.sleep(3)
												os.system('clear')
												main()
											else:
												if nomor == '12':
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
													time.sleep(1)
													print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
													time.sleep(1)
													print(G + "  [•]" + W + " selesai..")
													time.sleep(3)
													os.system('clear')
													main()
												else:
													if nomor == '13':
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
														time.sleep(1)
														print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
														time.sleep(1)
														print(G + "  [•]" + W + " selesai..")
														time.sleep(3)
														os.system('clear')
														main()
													else:
														if nomor == '14':
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
															time.sleep(1)
															print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
															time.sleep(1)
															print(G + "  [•]" + W + " selesai..")
															time.sleep(3)
															os.system('clear')
															main()
														else:
															if nomor == '15':
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																time.sleep(1)
																print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
																time.sleep(1)
																print(G + "  [•]" + W + " selesai..")
																time.sleep(3)
																os.system('clear')
																main()
															else:
																if nomor == '16':
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																	time.sleep(1)
																	print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
																	time.sleep(1)
																	print(G + "  [•]" + W + " selesai..")
																	time.sleep(3)
																	os.system('clear')
																	main()
																else:
																	if nomor == '17':
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																		time.sleep(1)
																		print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
																		time.sleep(1)
																		print(G + "  [•]" + W + " selesai..")
																		time.sleep(3)
																		os.system('clear')
																		main()
																	else:
																		if nomor == '18':
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																			time.sleep(1)
																			print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
																			time.sleep(1)
																			print(G + "  [•]" + W + " selesai..")
																			time.sleep(3)
																			os.system('clear')
																			main()
																		else:
																			if nomor == '19':
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																				time.sleep(1)
																				print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
																				time.sleep(1)
																				print(G + "  [•]" + W + " selesai..")
																				time.sleep(3)
																				os.system('clear')
																				main()
																			else:
																				if nomor == '20':
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [✓]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [√]" + W + " mengirim Trojan ke" + G , phone)
																					time.sleep(1)
																					print(G + "  [•]" + W + " Trojan terkirim ke" + G + "", phone , "" + W + "sebanyak" + G + "", nomor)
																					time.sleep(1)
																					print(G + "  [•]" + W + " selesai..")
																					time.sleep(3)
																					os.system('clear')
																					main()

# Malware area

def Malwer():
	p = ['628']
	mal = input(R + '\n [•]' + W + ' nomor: ' + R)
	ware = input(R + ' [•]' + W + ' banyak malware: [1-20] ' + R)
	time.sleep(1)
	if ware == '1':
		time.sleep(1)
		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
		time.sleep(1)
		print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
		time.sleep(1)
		print(R + "  [•]" + W + " selesai..")
		time.sleep(3)
		os.system('clear')
		main()
	else:
		if ware == '2':
			time.sleep(1)
			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
			time.sleep(1)
			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
			time.sleep(1)
			print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
			time.sleep(1)
			print(R + "  [•]" + W + " selesai..")
			time.sleep(3)
			os.system('clear')
			main()
		else:
			if ware == '3':
				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
				time.sleep(1)
				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
				time.sleep(1)
				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
				time.sleep(1)
				print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
				time.sleep(1)
				print(R + "  [•]" + W + " selesai..")
				time.sleep(3)
				os.system('clear')
				main()
			else:
				if ware == '4':
					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
					time.sleep(1)
					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
					time.sleep(1)
					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
					time.sleep(1)
					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
					time.sleep(1)
					print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
					time.sleep(1)
					print(R + "  [•]" + W + " selesai..")
					time.sleep(3)
					os.system('clear')
					main()
				else:
					if ware == '5':
						print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
						time.sleep(1)
						print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
						time.sleep(1)
						print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
						time.sleep(1)
						print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
						time.sleep(1)
						print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
						time.sleep(1)
						print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
						time.sleep(1)
						print(R + "  [•]" + W + " selesai..")
						time.sleep(3)
						os.system('clear')
						main()
					else:
						if ware == '6':
							print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
							time.sleep(1)
							print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
							time.sleep(1)
							print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
							time.sleep(1)
							print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
							time.sleep(1)
							print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
							time.sleep(1)
							print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
							time.sleep(1)
							print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
							time.sleep(1)
							print(R + "  [•]" + W + " selesai..")
							time.sleep(3)
							os.system('clear')
							main()
						else:
							if ware == '7':
								print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
								time.sleep(1)
								print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
								time.sleep(1)
								print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
								time.sleep(1)
								print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
								time.sleep(1)
								print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
								time.sleep(1)
								print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
								time.sleep(1)
								print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
								time.sleep(1)
								print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
								time.sleep(1)
								print(R + "  [•]" + W + " selesai..")
								time.sleep(3)
								os.system('clear')
								main()
							else:
								if ware == '8':
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
									time.sleep(1)
									print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
									time.sleep(1)
									print(R + "  [•]" + W + " selesai..")
									time.sleep(3)
									os.system('clear')
									main()
								else:
									if ware == '9':
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
										time.sleep(1)
										print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
										time.sleep(1)
										print(R + "  [•]" + W + " selesai..")
										time.sleep(3)
										os.system('clear')
										main()
									else:
										if ware == '10':
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
											time.sleep(1)
											print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
											time.sleep(1)
											print(R + "  [•]" + W + " selesai..")
											time.sleep(3)
											os.system('clear')
											main()
										else:
											if ware == '11':
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
												time.sleep(1)
												print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
												time.sleep(1)
												print(R + "  [•]" + W + " selesai..")
												time.sleep(3)
												os.system('clear')
												main()
											else:
												if ware == '12':
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
													time.sleep(1)
													print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
													time.sleep(1)
													print(R + "  [•]" + W + " selesai..")
													time.sleep(3)
													os.system('clear')
													main()
												else:
													if ware == '13':
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
														time.sleep(1)
														print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
														time.sleep(1)
														print(R + "  [•]" + W + " selesai..")
														time.sleep(3)
														os.system('clear')
														main()
													else:
														if ware == '14':
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
															time.sleep(1)
															print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
															time.sleep(1)
															print(R + "  [•]" + W + " selesai..")
															time.sleep(3)
															os.system('clear')
															main()
														else:
															if ware == '15':
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																time.sleep(1)
																print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
																time.sleep(1)
																print(R + "  [•]" + W + " selesai..")
																time.sleep(3)
																os.system('clear')
																main()
															else:
																if ware == '16':
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																	time.sleep(1)
																	print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
																	time.sleep(1)
																	print(R + "  [•]" + W + " selesai..")
																	time.sleep(3)
																	os.system('clear')
																	main()
																else:
																	if ware == '17':
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																		time.sleep(1)
																		print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
																		time.sleep(1)
																		print(R + "  [•]" + W + " selesai..")
																		time.sleep(3)
																		os.system('clear')
																		main()
																	else:
																		if ware == '18':
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																			time.sleep(1)
																			print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
																			time.sleep(1)
																			print(R + "  [•]" + W + " selesai..")
																			time.sleep(3)
																			os.system('clear')
																			main()
																		else:
																			if ware == '19':
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																				time.sleep(1)
																				print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
																				time.sleep(1)
																				print(R + "  [•]" + W + " selesai..")
																				time.sleep(3)
																				os.system('clear')
																				main()
																			else:
																				if ware == '20':
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [✓]" + W + " mengirim Malware ke" + R , mal)
																					time.sleep(1)
																					print(R + "  [•]" + W + " Malware terkirim ke" + R + "", mal , "" + W + "sebanyak" + R + "", mal)
																					time.sleep(1)
																					print(R + "  [•]" + W + " selesai..")
																					time.sleep(3)
																					os.system('clear')
																					main()
														
				

# W0rm area

def W0rm():
	Oh = ['628']
	w0 = input(Y + '\n [•]' + W + ' nomor: ' + Y)
	rm = input(Y + ' [•]' + W + ' banyak worm: [1-20] ' + Y)
	time.sleep(1)
	if rm == '1':
		time.sleep(1)
		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
		time.sleep(1)
		print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
		time.sleep(1)
		print(Y + "  [•]" + W + " selesai..")
		time.sleep(3)
		os.system('clear')
		main()
	else:
		if rm == '2':
			time.sleep(1)
			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
			time.sleep(1)
			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
			time.sleep(1)
			print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
			time.sleep(1)
			print(Y + "  [•]" + W + " selesai..")
			time.sleep(3)
			os.system('clear')
			main()
		else:
			if rm == '3':
				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
				time.sleep(1)
				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
				time.sleep(1)
				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
				time.sleep(1)
				print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
				time.sleep(1)
				print(Y + "  [•]" + W + " selesai..")
				time.sleep(3)
				os.system('clear')
				main()
			else:
				if rm == '4':
					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
					time.sleep(1)
					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
					time.sleep(1)
					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
					time.sleep(1)
					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
					time.sleep(1)
					print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
					time.sleep(1)
					print(Y + "  [•]" + W + " selesai..")
					time.sleep(3)
					os.system('clear')
					main()
				else:
					if rm == '5':
						print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
						time.sleep(1)
						print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
						time.sleep(1)
						print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
						time.sleep(1)
						print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
						time.sleep(1)
						print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
						time.sleep(1)
						print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
						time.sleep(1)
						print(Y + "  [•]" + W + " selesai..")
						time.sleep(3)
						os.system('clear')
						main()
					else:
						if rm == '6':
							print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
							time.sleep(1)
							print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
							time.sleep(1)
							print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
							time.sleep(1)
							print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
							time.sleep(1)
							print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
							time.sleep(1)
							print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
							time.sleep(1)
							print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
							time.sleep(1)
							print(Y + "  [•]" + W + " selesai..")
							time.sleep(3)
							os.system('clear')
							main()
						else:
							if rm == '7':
								print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
								time.sleep(1)
								print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
								time.sleep(1)
								print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
								time.sleep(1)
								print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
								time.sleep(1)
								print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
								time.sleep(1)
								print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
								time.sleep(1)
								print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
								time.sleep(1)
								print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
								time.sleep(1)
								print(Y + "  [•]" + W + " selesai..")
								time.sleep(3)
								os.system('clear')
								main()
							else:
								if rm == '8':
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
									time.sleep(1)
									print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
									time.sleep(1)
									print(Y + "  [•]" + W + " selesai..")
									time.sleep(3)
									os.system('clear')
									main()
								else:
									if rm == '9':
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
										time.sleep(1)
										print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
										time.sleep(1)
										print(Y + "  [•]" + W + " selesai..")
										time.sleep(3)
										os.system('clear')
										main()
									else:
										if rm == '10':
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
											time.sleep(1)
											print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
											time.sleep(1)
											print(Y + "  [•]" + W + " selesai..")
											time.sleep(3)
											os.system('clear')
											main()
										else:
											if rm == '11':
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
												time.sleep(1)
												print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
												time.sleep(1)
												print(Y + "  [•]" + W + " selesai..")
												time.sleep(3)
												os.system('clear')
												main()
											else:
												if rm == '12':
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
													time.sleep(1)
													print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
													time.sleep(1)
													print(Y + "  [•]" + W + " selesai..")
													time.sleep(3)
													os.system('clear')
													main()
												else:
													if rm == '13':
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
														time.sleep(1)
														print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
														time.sleep(1)
														print(Y + "  [•]" + W + " selesai..")
														time.sleep(3)
														os.system('clear')
														main()
													else:
														if rm == '14':
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
															time.sleep(1)
															print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
															time.sleep(1)
															print(Y + "  [•]" + W + " selesai..")
															time.sleep(3)
															os.system('clear')
															main()
														else:
															if rm == '15':
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																time.sleep(1)
																print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
																time.sleep(1)
																print(Y + "  [•]" + W + " selesai..")
																time.sleep(3)
																os.system('clear')
																main()
															else:
																if rm == '16':
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																	time.sleep(1)
																	print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
																	time.sleep(1)
																	print(Y + "  [•]" + W + " selesai..")
																	time.sleep(3)
																	os.system('clear')
																	main()
																else:
																	if rm == '17':
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																		time.sleep(1)
																		print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
																		time.sleep(1)
																		print(Y + "  [•]" + W + " selesai..")
																		time.sleep(3)
																		os.system('clear')
																		main()
																	else:
																		if rm == '18':
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																			time.sleep(1)
																			print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
																			time.sleep(1)
																			print(Y + "  [•]" + W + " selesai..")
																			time.sleep(3)
																			os.system('clear')
																			main()
																		else:
																			if rm == '19':
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																				time.sleep(1)
																				print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
																				time.sleep(1)
																				print(Y + "  [•]" + W + " selesai..")
																				time.sleep(3)
																				os.system('clear')
																				main()
																			else:
																				if rm == '20':
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [✓]" + W + " mengirim worm ke" + Y , w0)
																					time.sleep(1)
																					print(Y + "  [•]" + W + " worm terkirim ke" + Y + "", w0 , "" + W + "sebanyak" + Y + "", rm)
																					time.sleep(1)
																					print(Y + "  [•]" + W + " selesai..")
																					time.sleep(3)
																					os.system('clear')
																					main()
	
	
main()